//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class studinfo
    {
        public int Id { get; set; }
        public string stuname { get; set; }
        public string fathername { get; set; }
        public string mothername { get; set; }
        public string address { get; set; }
        public Nullable<int> contactNo { get; set; }
        public string email { get; set; }
        public string DepartMent { get; set; }
    }
}
